---

pool: 
 name: Azure Pipelines
 vmImage: ubuntu-latest

trigger:
  - main
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '**/target/*.war'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'gol'
    publishLocation: 'Container'

      
