---

pool: 
 name: Azure Pipelines
 vmImage: ubuntu-latest

trigger:
  - main
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenVersionOption: 'Default'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
- task: CopyFiles@2
  inputs:
    Contents: '**/target/*.war'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'gol'
    publishLocation: 'Container'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '100'

      
