---

pool: 
 name: Azure Pipeline
 vmImage: ubuntu-latest

trigger:
  - main
steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'hema789 / gameoflife'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      
