---
trigger:
  - master
jobs:
  - job: "build gol"
    displayName: build maven package for gameoflife
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/"
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'


   